#!/usr/bin/env bash
# render-agents.sh — regenerate $PROJECTS_ROOT/AGENTS.md from CLAUDE.md + the
# Codex-only addendum, so the two can never silently drift.
#
# AGENTS.md is GENERATED. Tools that read AGENTS.md natively (Codex, and other
# tool-agnostic agents) get CLAUDE.md's shared rules PLUS a small Codex-specific
# delta. The ONLY hand-edited sources are:
#   - $PROJECTS_ROOT/CLAUDE.md          (shared rules; Claude reads this directly)
#   - $PROJECTS_ROOT/AGENTS.addendum.md (Codex-only delta appended after CLAUDE.md)
# Never hand-edit AGENTS.md — doctor.sh (code 15) fails the build if it drifts
# from `CLAUDE.md + addendum`.
#
# Usage:
#   bash render-agents.sh            # rewrite AGENTS.md if stale (idempotent)
#   bash render-agents.sh --check    # exit 1 if AGENTS.md is stale; write nothing
#   PROJECTS_ROOT=/path bash render-agents.sh
#
# Called by install.sh; safe to run standalone. No-ops cleanly on a host that
# clones dotfiles but not my-projects.

set -euo pipefail

# Workspace-root discovery: env override, then conventional fallback.
# Contract: 00_SYSTEM/anders-config/rules/workspace-root-discovery.md.
PROJECTS_ROOT="${PROJECTS_ROOT:-$HOME/Code/my-projects}"
CLAUDE="$PROJECTS_ROOT/CLAUDE.md"
ADDENDUM="$PROJECTS_ROOT/AGENTS.addendum.md"
OUT="$PROJECTS_ROOT/AGENTS.md"

# No workspace / no source on this host → nothing to render. Not an error.
if [[ ! -d "$PROJECTS_ROOT" || ! -f "$CLAUDE" ]]; then
  echo "render-agents: no workspace CLAUDE.md at $PROJECTS_ROOT — skipping AGENTS.md render"
  exit 0
fi

# The generated AGENTS.md = banner + CLAUDE.md (verbatim) + addendum (if present).
render() {
  printf '%s\n' '<!-- AUTOGENERATED by anders-dotfiles/context-sync/render-agents.sh.'
  printf '%s\n' '     DO NOT EDIT AGENTS.md directly. Edit CLAUDE.md (shared rules) or'
  printf '%s\n' '     AGENTS.addendum.md (Codex-only delta), then run render-agents.sh.'
  printf '%s\n\n' '     doctor.sh code 15 fails the build if AGENTS.md drifts from source. -->'
  cat "$CLAUDE"
  if [[ -f "$ADDENDUM" && -s "$ADDENDUM" ]]; then
    printf '\n'
    cat "$ADDENDUM"
  fi
}

if [[ "${1:-}" == "--check" ]]; then
  if [[ -f "$OUT" ]] && diff <(render) "$OUT" >/dev/null 2>&1; then
    exit 0
  fi
  echo "render-agents: AGENTS.md is STALE vs CLAUDE.md + AGENTS.addendum.md — run: bash render-agents.sh" >&2
  exit 1
fi

# Idempotent write: skip if already current.
if [[ -f "$OUT" ]] && diff <(render) "$OUT" >/dev/null 2>&1; then
  echo "render-agents: $OUT already current — no change"
  exit 0
fi

tmp="$(mktemp "${OUT}.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
render > "$tmp"
chmod 644 "$tmp"   # mktemp creates 0600; AGENTS.md is a public committed doc, not a secret
mv "$tmp" "$OUT"
trap - EXIT
echo "render-agents: wrote $OUT"
