#!/usr/bin/env bash
# render-claude.sh — regenerate $PROJECTS_ROOT/CLAUDE.md from AGENTS.md + the
# Claude-only addendum, so the two can never silently drift.
#
# INVERSION of render-agents.sh (2026-05-31): AGENTS.md is now the hand-edited
# canonical source (the cross-tool standard Codex/Cursor read natively). CLAUDE.md
# is GENERATED so Claude Code gets AGENTS.md's shared rules PLUS a small Claude-only
# delta (e.g. @import directives that only Claude Code parses). The ONLY hand-edited
# sources are:
#   - $PROJECTS_ROOT/AGENTS.md           (shared canon; Codex/Cursor read this directly)
#   - $PROJECTS_ROOT/CLAUDE.addendum.md  (Claude-only delta appended after AGENTS.md)
# Never hand-edit CLAUDE.md — doctor.sh (code 15) fails the build if it drifts
# from `AGENTS.md + addendum`.
#
# Gap-safety (per /cowork Gemini pre-flight 2026-05-31): --check renders FRESH and
# diffs against the committed CLAUDE.md — never against a stale temp — so a
# hand-edited CLAUDE.md cannot silently match flawed cached output.
#
# Usage:
#   bash render-claude.sh            # rewrite CLAUDE.md if stale (idempotent)
#   bash render-claude.sh --check    # 0=in sync · 1=stale · 2=error; writes nothing
#   PROJECTS_ROOT=/path bash render-claude.sh
#
# Called by install.sh; safe to run standalone. No-ops cleanly on a host that
# clones dotfiles but not my-projects.

set -euo pipefail

# Workspace-root discovery: env override, then conventional fallback.
# Contract: 00_SYSTEM/anders-config/rules/workspace-root-discovery.md.
PROJECTS_ROOT="${PROJECTS_ROOT:-$HOME/Code/my-projects}"
AGENTS="$PROJECTS_ROOT/AGENTS.md"
ADDENDUM="$PROJECTS_ROOT/CLAUDE.addendum.md"
OUT="$PROJECTS_ROOT/CLAUDE.md"

# No workspace / no source on this host → nothing to render. Not an error.
if [[ ! -d "$PROJECTS_ROOT" || ! -f "$AGENTS" ]]; then
  echo "render-claude: no workspace AGENTS.md at $PROJECTS_ROOT — skipping CLAUDE.md render"
  exit 0
fi

# The generated CLAUDE.md = banner + AGENTS.md (verbatim) + addendum (if present).
render() {
  printf '%s\n' '<!-- AUTOGENERATED by anders-dotfiles/context-sync/render-claude.sh.'
  printf '%s\n' '     DO NOT EDIT CLAUDE.md directly. Edit AGENTS.md (shared canon) or'
  printf '%s\n' '     CLAUDE.addendum.md (Claude-only delta), then run render-claude.sh.'
  printf '%s\n\n' '     doctor.sh code 15 fails the build if CLAUDE.md drifts from source. -->'
  cat "$AGENTS"
  if [[ -f "$ADDENDUM" && -s "$ADDENDUM" ]]; then
    printf '\n'
    cat "$ADDENDUM"
  fi
}

if [[ "${1:-}" == "--check" ]]; then
  # Distinguish three states so callers (doctor.sh) give the right remediation:
  #   0 = in sync · 1 = stale (re-render) · 2 = error (source/output unreadable)
  # render() is captured explicitly so a failing source read surfaces as 2, not
  # a false "stale" — process substitution would hide the failure from set -e.
  if [[ ! -f "$OUT" ]]; then
    echo "render-claude: CLAUDE.md missing — run: bash render-claude.sh" >&2; exit 1
  fi
  rendered="$(render)" || { echo "render-claude: ERROR — cannot render from AGENTS.md/CLAUDE.addendum.md (unreadable?)" >&2; exit 2; }
  current="$(cat "$OUT")"  || { echo "render-claude: ERROR — cannot read $OUT" >&2; exit 2; }
  if [[ "$rendered" == "$current" ]]; then exit 0; fi
  echo "render-claude: CLAUDE.md is STALE vs AGENTS.md + CLAUDE.addendum.md — run: bash render-claude.sh" >&2
  exit 1
fi

# Idempotent write: skip if already current.
if [[ -f "$OUT" ]] && diff <(render) "$OUT" >/dev/null 2>&1; then
  echo "render-claude: $OUT already current — no change"
  exit 0
fi

tmp="$(mktemp "${OUT}.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
render > "$tmp"
chmod 644 "$tmp"   # mktemp creates 0600; CLAUDE.md is a public committed doc, not a secret
mv "$tmp" "$OUT"
trap - EXIT
echo "render-claude: wrote $OUT"
